import type { RealSuitcase } from './types';

export const backpackModels = [
  {
    id: 'travel-backpack',
    title: { ru: 'Дорожный рюкзак', en: 'Travel backpack' },
    author: 'J-Toastie',
    license: 'CC-BY 3.0',
    modelUrl: '/models/suitcases/travel-backpack.glb',
    imageUrl: '/images/suitcases/travel-backpack.png',
    sourceUrl: 'https://poly.pizza/m/uRRsiIZKHG',
  },
  {
    id: 'backpack-quaternius-rolltop-blue',
    title: { ru: 'Высокий синий городской рюкзак', en: 'Tall blue city backpack' },
    author: 'Quaternius · modified',
    license: 'CC0 1.0',
    modelUrl: '/models/suitcases/backpack-quaternius-rolltop-blue.glb',
    imageUrl: '/images/suitcases/backpack-quaternius-rolltop-blue.png',
    sourceUrl: 'https://poly.pizza/m/2g9Jm7kvIU',
  },
  {
    id: 'backpack-quaternius-01',
    title: { ru: 'Компактный рюкзак', en: 'Compact backpack' },
    author: 'Quaternius',
    license: 'CC0 1.0',
    modelUrl: '/models/suitcases/backpack-quaternius-01.glb',
    imageUrl: '/images/suitcases/backpack-quaternius-01.png',
    sourceUrl: 'https://poly.pizza/m/2g9Jm7kvIU',
  },
  {
    id: 'backpack-alex',
    title: { ru: 'Городской рюкзак', en: 'Urban backpack' },
    author: 'Alex Safayan',
    license: 'CC-BY 3.0',
    modelUrl: '/models/suitcases/backpack-alex.glb',
    imageUrl: '/images/suitcases/backpack-alex.png',
    sourceUrl: 'https://poly.pizza/m/5UQVd1Agl11',
  },
  {
    id: 'backpack-quaternius-panel-red',
    title: { ru: 'Узкий красный походный рюкзак', en: 'Narrow red trail backpack' },
    author: 'Quaternius · modified',
    license: 'CC0 1.0',
    modelUrl: '/models/suitcases/backpack-quaternius-panel-red.glb',
    imageUrl: '/images/suitcases/backpack-quaternius-panel-red.png',
    sourceUrl: 'https://poly.pizza/m/vF7TuXCPDH',
  },
  {
    id: 'backpack-quaternius-02',
    title: { ru: 'Походный рюкзак', en: 'Trail backpack' },
    author: 'Quaternius',
    license: 'CC0 1.0',
    modelUrl: '/models/suitcases/backpack-quaternius-02.glb',
    imageUrl: '/images/suitcases/backpack-quaternius-02.png',
    sourceUrl: 'https://poly.pizza/m/vF7TuXCPDH',
  },
  {
    id: 'backpack-flashlight',
    title: { ru: 'Рюкзак с фонариком', en: 'Backpack with flashlight' },
    author: 'Don Carson',
    license: 'CC-BY 3.0',
    modelUrl: '/models/suitcases/backpack-flashlight.glb',
    imageUrl: '/images/suitcases/backpack-flashlight.png',
    sourceUrl: 'https://poly.pizza/m/aVCjXvxs6sP',
  },
  {
    id: 'backpack-jeremy',
    title: { ru: 'Кожаный городской рюкзак', en: 'Leather city backpack' },
    author: 'jeremy',
    license: 'CC-BY 3.0',
    modelUrl: '/models/suitcases/backpack-jeremy.glb',
    imageUrl: '/images/suitcases/backpack-jeremy.png',
    sourceUrl: 'https://poly.pizza/m/cJFKpOZzl8s',
  },
  {
    id: 'hiking-backpack',
    title: { ru: 'Большой туристический рюкзак', en: 'Large hiking backpack' },
    author: 'Voxel_dev',
    license: 'CC0 1.0',
    modelUrl: '/models/suitcases/hiking-backpack.glb',
    imageUrl: '/images/suitcases/hiking-backpack.png',
    sourceUrl: 'https://poly.pizza/m/pVuHdEBRUs',
  },
] satisfies readonly RealSuitcase[];
