import type { RealSuitcase } from './types';

export const briefcaseModels = [
  {
    id: 'animated-briefcase',
    title: { ru: 'Анимированный портфель', en: 'Animated briefcase' },
    author: 'reyshapes',
    license: 'CC0 1.0',
    modelUrl: '/models/suitcases/animated-briefcase.glb',
    imageUrl: '/images/suitcases/animated-briefcase.png',
    sourceUrl: 'https://poly.pizza/m/3fFsumkkQD',
    animations: { open: 'open', close: 'closed' },
  },
  {
    id: 'business-briefcase',
    title: { ru: 'Деловой портфель', en: 'Business briefcase' },
    author: 'Jarlan Perez',
    license: 'CC-BY 3.0',
    modelUrl: '/models/suitcases/business-briefcase.glb',
    imageUrl: '/images/suitcases/business-briefcase.png',
    sourceUrl: 'https://poly.pizza/m/9Gf_88C9rxF',
  },
  {
    id: 'leather-briefcase',
    title: { ru: 'Кожаный портфель', en: 'Leather briefcase' },
    author: 'jeremy',
    license: 'CC-BY 3.0',
    modelUrl: '/models/suitcases/leather-briefcase.glb',
    imageUrl: '/images/suitcases/leather-briefcase.png',
    sourceUrl: 'https://poly.pizza/m/8j8-b-RqJ76',
  },
  {
    id: 'briefcase-google-01',
    title: { ru: 'Офисный портфель', en: 'Office briefcase' },
    author: 'Poly by Google',
    license: 'CC-BY 3.0',
    modelUrl: '/models/suitcases/briefcase-google-01.glb',
    imageUrl: '/images/suitcases/briefcase-google-01.png',
    sourceUrl: 'https://poly.pizza/m/cKZ9BZNK1JE',
  },
  {
    id: 'briefcase-google-02',
    title: { ru: 'Компактный портфель', en: 'Compact briefcase' },
    author: 'Poly by Google',
    license: 'CC-BY 3.0',
    modelUrl: '/models/suitcases/briefcase-google-02.glb',
    imageUrl: '/images/suitcases/briefcase-google-02.png',
    sourceUrl: 'https://poly.pizza/m/7Y-V-rdyvi6',
  },
] satisfies readonly RealSuitcase[];
