import type { RealSuitcase } from './types';

export const bagModels = [
  {
    id: 'duffel-bag',
    title: { ru: 'Спортивная сумка', en: 'Duffel bag' },
    author: 'accidentallyc',
    license: 'CC0 1.0',
    modelUrl: '/models/suitcases/duffel-bag.glb',
    imageUrl: '/images/suitcases/duffel-bag.png',
    sourceUrl: 'https://poly.pizza/m/rysPhwuIP4',
  },
  {
    id: 'laptop-bag',
    title: { ru: 'Сумка для ноутбука', en: 'Laptop bag' },
    author: 'jeremy',
    license: 'CC-BY 3.0',
    modelUrl: '/models/suitcases/laptop-bag.glb',
    imageUrl: '/images/suitcases/laptop-bag.png',
    sourceUrl: 'https://poly.pizza/m/ehg2hPUQ1uc',
  },
  {
    id: 'purse-01',
    title: { ru: 'Дорожная дамская сумка', en: 'Travel purse' },
    author: 'jeremy',
    license: 'CC-BY 3.0',
    modelUrl: '/models/suitcases/purse-01.glb',
    imageUrl: '/images/suitcases/purse-01.png',
    sourceUrl: 'https://poly.pizza/m/2dTPEuZyLyJ',
  },
  {
    id: 'travel-bag-01',
    title: { ru: 'Наплечная дорожная сумка', en: 'Shoulder travel bag' },
    author: 'Quaternius',
    license: 'CC0 1.0',
    modelUrl: '/models/suitcases/travel-bag-01.glb',
    imageUrl: '/images/suitcases/travel-bag-01.png',
    sourceUrl: 'https://poly.pizza/m/Wq1JPPqHZS',
  },
  {
    id: 'cabin-roller-silver',
    title: { ru: 'Серебристый салонный чемодан', en: 'Silver cabin roller' },
    author: 'get wilde · modified',
    license: 'CC-BY 3.0',
    modelUrl: '/models/suitcases/cabin-roller-silver.glb',
    imageUrl: '/images/suitcases/cabin-roller-silver.png',
    sourceUrl: 'https://poly.pizza/m/axVdRGg-Lbl',
    tint: '#aeb6c1',
  },
  {
    id: 'laptop-bag-google',
    title: { ru: 'Жёсткая сумка для ноутбука', en: 'Hard laptop bag' },
    author: 'Poly by Google',
    license: 'CC-BY 3.0',
    modelUrl: '/models/suitcases/laptop-bag-google.glb',
    imageUrl: '/images/suitcases/laptop-bag-google.png',
    sourceUrl: 'https://poly.pizza/m/af_ElXGyq5b',
  },
  {
    id: 'hardshell-spinner-cobalt',
    title: { ru: 'Кобальтовый чемодан-спиннер', en: 'Cobalt hardshell spinner' },
    author: 'J-Toastie · modified',
    license: 'CC-BY 3.0',
    modelUrl: '/models/suitcases/hardshell-spinner-cobalt.glb',
    imageUrl: '/images/suitcases/hardshell-spinner-cobalt.png',
    sourceUrl: 'https://poly.pizza/m/041xs8FnZZ',
    tint: '#315aa8',
  },
  {
    id: 'fabric-trolley-amber',
    title: { ru: 'Янтарный тканевый чемодан', en: 'Amber fabric trolley' },
    author: 'Poly by Google · modified',
    license: 'CC-BY 3.0',
    modelUrl: '/models/suitcases/fabric-trolley-amber.glb',
    imageUrl: '/images/suitcases/fabric-trolley-amber.png',
    sourceUrl: 'https://poly.pizza/m/ezEfa_eupwK',
    tint: '#c77a2c',
  },
  {
    id: 'executive-briefcase-charcoal',
    title: { ru: 'Графитовый деловой портфель', en: 'Charcoal executive briefcase' },
    author: 'Jarlan Perez · modified',
    license: 'CC-BY 3.0',
    modelUrl: '/models/suitcases/executive-briefcase-charcoal.glb',
    imageUrl: '/images/suitcases/executive-briefcase-charcoal.png',
    sourceUrl: 'https://poly.pizza/m/9Gf_88C9rxF',
    tint: '#39404a',
  },
  {
    id: 'travel-bag-organizer-green',
    title: { ru: 'Широкая зелёная дорожная сумка', en: 'Wide green travel bag' },
    author: 'Quaternius · modified',
    license: 'CC0 1.0',
    modelUrl: '/models/suitcases/travel-bag-organizer-green.glb',
    imageUrl: '/images/suitcases/travel-bag-organizer-green.png',
    sourceUrl: 'https://poly.pizza/m/Wq1JPPqHZS',
  },
  {
    id: 'hiking-pack-slate',
    title: { ru: 'Сланцевый туристический рюкзак', en: 'Slate hiking pack' },
    author: 'Voxel_dev · modified',
    license: 'CC0 1.0',
    modelUrl: '/models/suitcases/hiking-pack-slate.glb',
    imageUrl: '/images/suitcases/hiking-pack-slate.png',
    sourceUrl: 'https://poly.pizza/m/pVuHdEBRUs',
    tint: '#536875',
  },
] satisfies readonly RealSuitcase[];
