import type { RealSuitcase } from './types';

export const colorEditions = [
  {
    id: 'airport-luggage-strapped-red',
    title: { ru: 'Широкий красный тканевый чемодан', en: 'Wide red fabric suitcase' },
    author: 'Poly by Google · modified',
    license: 'CC-BY 3.0',
    modelUrl: '/models/suitcases/airport-luggage-strapped-red.glb',
    imageUrl: '/images/suitcases/airport-luggage-strapped-red.png',
    sourceUrl: 'https://poly.pizza/m/ezEfa_eupwK',
    tint: '#f06058',
  },
  {
    id: 'leather-briefcase-pocket-teal',
    title: { ru: 'Низкий бирюзовый кожаный портфель', en: 'Low-profile teal briefcase' },
    author: 'jeremy · modified',
    license: 'CC-BY 3.0',
    modelUrl: '/models/suitcases/leather-briefcase-pocket-teal.glb',
    imageUrl: '/images/suitcases/leather-briefcase-pocket-teal.png',
    sourceUrl: 'https://poly.pizza/m/8j8-b-RqJ76',
    tint: '#168f8a',
  },
  {
    id: 'travel-suitcase-guarded-yellow',
    title: { ru: 'Высокий жёлтый дорожный чемодан', en: 'Tall yellow travel suitcase' },
    author: 'J-Toastie · modified',
    license: 'CC-BY 3.0',
    modelUrl: '/models/suitcases/travel-suitcase-guarded-yellow.glb',
    imageUrl: '/images/suitcases/travel-suitcase-guarded-yellow.png',
    sourceUrl: 'https://poly.pizza/m/041xs8FnZZ',
    tint: '#d9a514',
  },
  {
    id: 'travel-backpack-pocket-coral',
    title: { ru: 'Высокий коралловый дорожный рюкзак', en: 'Tall coral travel backpack' },
    author: 'J-Toastie · modified',
    license: 'CC-BY 3.0',
    modelUrl: '/models/suitcases/travel-backpack-pocket-coral.glb',
    imageUrl: '/images/suitcases/travel-backpack-pocket-coral.png',
    sourceUrl: 'https://poly.pizza/m/uRRsiIZKHG',
    tint: '#d96b55',
  },
  {
    id: 'carry-on-ribbed-navy',
    title: { ru: 'Тонкий синий чемодан для ручной клади', en: 'Slim navy carry-on' },
    author: 'get wilde · modified',
    license: 'CC-BY 3.0',
    modelUrl: '/models/suitcases/carry-on-ribbed-navy.glb',
    imageUrl: '/images/suitcases/carry-on-ribbed-navy.png',
    sourceUrl: 'https://poly.pizza/m/axVdRGg-Lbl',
    tint: '#234e8c',
  },
  {
    id: 'business-briefcase-reinforced-emerald',
    title: { ru: 'Широкий зелёный деловой портфель', en: 'Wide emerald briefcase' },
    author: 'Jarlan Perez · modified',
    license: 'CC-BY 3.0',
    modelUrl: '/models/suitcases/business-briefcase-reinforced-emerald.glb',
    imageUrl: '/images/suitcases/business-briefcase-reinforced-emerald.png',
    sourceUrl: 'https://poly.pizza/m/9Gf_88C9rxF',
    tint: '#26845b',
  },
  {
    id: 'modern-suitcase-panel-graphite',
    title: { ru: 'Широкий графитовый чемодан', en: 'Wide graphite suitcase' },
    author: 'smallbigsquare · modified',
    license: 'CC0 1.0',
    modelUrl: '/models/suitcases/modern-suitcase-panel-graphite.glb',
    imageUrl: '/images/suitcases/modern-suitcase-panel-graphite.png',
    sourceUrl: 'https://poly.pizza/m/7DsKpns9FM',
    tint: '#2d3440',
  },
  {
    id: 'laptop-bag-strap-burgundy',
    title: { ru: 'Широкая бордовая сумка для ноутбука', en: 'Wide burgundy laptop bag' },
    author: 'Poly by Google · modified',
    license: 'CC-BY 3.0',
    modelUrl: '/models/suitcases/laptop-bag-strap-burgundy.glb',
    imageUrl: '/images/suitcases/laptop-bag-strap-burgundy.png',
    sourceUrl: 'https://poly.pizza/m/af_ElXGyq5b',
    tint: '#7e263e',
  },
  {
    id: 'backpack-sidepockets-olive',
    title: { ru: 'Высокий оливковый городской рюкзак', en: 'Tall olive city backpack' },
    author: 'Alex Safayan · modified',
    license: 'CC-BY 3.0',
    modelUrl: '/models/suitcases/backpack-sidepockets-olive.glb',
    imageUrl: '/images/suitcases/backpack-sidepockets-olive.png',
    sourceUrl: 'https://poly.pizza/m/5UQVd1Agl11',
    tint: '#4e6f3b',
  },
  {
    id: 'duffel-bag-banded-orange',
    title: { ru: 'Длинная оранжевая спортивная сумка', en: 'Long orange duffel bag' },
    author: 'accidentallyc · modified',
    license: 'CC0 1.0',
    modelUrl: '/models/suitcases/duffel-bag-banded-orange.glb',
    imageUrl: '/images/suitcases/duffel-bag-banded-orange.png',
    sourceUrl: 'https://poly.pizza/m/rysPhwuIP4',
    tint: '#d86f22',
  },
] satisfies readonly RealSuitcase[];
